### ISSUE TITLE
Nahrat a sloucit nejnovejsi variantu zpravy

### ISSUE THREAD

**Issue by VojtechMyslivec** [VojtechMyslivec/PAP-NCG#7]
To, co jsi @novyzde3 posilal Simeckovi, neni na gitu. Upravil jsem zpravu tak, jak jsem posilal v e-mailu, tak tam, prosim, pushni ty posledni zmeny, ktere mas asi jen lokalne.
V.

**Comment by novyzde3** [comment]
Nejnovejsi verze by mela byt na GITu lokalne nic nemam. TO co jsme posilal Simeckovi je i na GITu az na jeden odstavec Optimalizace vektorizace, ktery asi zmizel, kdyz si to presouval. Tak jsme ho tam nahral zpet.
